import {Writer} from '@jsonjoy.com/util/lib/buffers/Writer';
import {CliCodecs} from './CliCodecs';
import {CliCodecCbor} from './codecs/cbor';
import {CliCodecJson} from './codecs/json';
import {CliCodecJson2} from './codecs/json2';
import {CliCodecJson4} from './codecs/json4';
import {CliCodecMsgpack} from './codecs/msgpack';
import {CliCodecRaw} from './codecs/raw';
import {CliCodecText} from './codecs/text';
import {CliCodecTree} from './codecs/tree';
import {CliCodecUbjson} from './codecs/ubjson';
import {CliCodecHex} from './codecs/hex';
import {CliCodecDagJson} from './codecs/dag-json';
import {CliCodecDagCbor} from './codecs/dag-cbor';
import {CliCodecBencode} from './codecs/bencode';
import {CliCodecResp} from './codecs/resp';
import {CliCodecBson} from './codecs/bson';
import {CliCodecEjson} from './codecs/ejson';

export const defaultCodecs = new CliCodecs();

const writer = new Writer(16 * 1024);
defaultCodecs.register(new CliCodecJson(writer));
defaultCodecs.register(new CliCodecJson2(writer));
defaultCodecs.register(new CliCodecJson4(writer));
defaultCodecs.register(new CliCodecCbor(writer));
defaultCodecs.register(new CliCodecMsgpack(writer));
defaultCodecs.register(new CliCodecUbjson(writer));
defaultCodecs.register(new CliCodecText());
defaultCodecs.register(new CliCodecTree());
defaultCodecs.register(new CliCodecRaw());
defaultCodecs.register(new CliCodecHex());
defaultCodecs.register(new CliCodecDagJson(writer));
defaultCodecs.register(new CliCodecDagCbor(writer));
defaultCodecs.register(new CliCodecBencode(writer));
defaultCodecs.register(new CliCodecResp(writer));
defaultCodecs.register(new CliCodecBson(writer));
defaultCodecs.register(new CliCodecEjson(writer));
